set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(MINGW_PREFIX "x86_64-w64-mingw32" CACHE STRING "MinGW-w64 triplet prefix")
set(MINGW_SYSROOT "/usr/${MINGW_PREFIX}" CACHE PATH "MinGW-w64 sysroot path")

if (NOT CMAKE_C_COMPILER)
    set(CMAKE_C_COMPILER "${MINGW_PREFIX}-gcc")
endif()
if (NOT CMAKE_CXX_COMPILER)
    set(CMAKE_CXX_COMPILER "${MINGW_PREFIX}-g++")
endif()
if (NOT CMAKE_RC_COMPILER)
    set(CMAKE_RC_COMPILER "${MINGW_PREFIX}-windres")
endif()

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if (EXISTS "${MINGW_SYSROOT}")
    list(APPEND CMAKE_FIND_ROOT_PATH "${MINGW_SYSROOT}")
endif()

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
